name: use already created workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name to pass to the reusable workflow
        required: false
        default: Mayank
        type: string

jobs:
  call-reusable-workflow:
    uses: mayankbansa0105/gh-study/.github/workflows/Reusable-internal-call.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets: inherit
