name: App CI

on:
  push:
  workflow_dispatch:

jobs:
  call-hello:
    uses: mayankbansa0105/gh-study/.github/workflows/reusable-hello.yml@main
    with:
      name: "Mayank"

  print-result:
    needs: call-hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Got back -> ${{ needs.call-hello.outputs.greeting }}"